/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.SQLException;
import servicio.Conexion;

/**
 *
 * @author kuroy
 */
public class formModEvento extends javax.swing.JPanel {
    public javax.swing.table.DefaultTableModel tableModelAct;
    public javax.swing.table.DefaultTableModel tableModelArt;
    /**
     * Creates new form formModEvento2
     */
    public formModEvento() {
        initComponents();
        this.cmbMontaje.addItem("");
        tableModelAct = (javax.swing.table.DefaultTableModel)this.tableActividades.getModel();
        tableModelArt = (javax.swing.table.DefaultTableModel)this.tableArticulo.getModel();
    }

    public void initListener(java.awt.event.ActionListener e){
        this.cmbMontaje.addActionListener(e);
        this.btnAddAct.addActionListener(e);
        this.btnAddArt.addActionListener(e);
        this.btnBus.addActionListener(e);
        this.btnDelAct.addActionListener(e);
        this.btnDelArt.addActionListener(e);
        this.btnCancelar.addActionListener(e);
        this.btnGuardar.addActionListener(e);
    }
    
    public void clear(){
        this.tableModelAct.setRowCount(0);
        this.tableModelAct.setRowCount(0);
        this.txtAbonar.setText("");
        this.txtDoc.setText("");
        this.txtHoraInicio.setText("");
        this.txtMontoAbonado.setText("");
        this.txtPrecioTotal.setText("");
    }
    
    private void removeItems(){
        for(Integer i=this.cmbMontaje.getItemCount()-1; i>0; i--){
            this.cmbMontaje.removeItemAt(i);
        }
        this.tableModelAct.setRowCount(0);
        this.tableModelArt.setRowCount(0);
    }
    
    public void addAllArticulo(java.util.ArrayList<modelo.ArticuloCliente> articulos){
        for(modelo.ArticuloCliente articulo : articulos){
            if(articulo.getTipoArticulo().equals(util.TipoArticulo.MONTAJE)){
                this.cmbMontaje.setSelectedIndex(this.index(articulo.getNombre()));
                try{
                    this.lblPrecioMontaje.setText(this.getPrecio(articulo.getNombre()));
                }catch(SQLException err){
                }
            }
            Object data[] = {articulo.getNombre(), articulo.getCantidad(), articulo.getCosto()};
            this.tableModelArt.addRow(data);
        }
    }
    
    public void addAllActividad(java.util.ArrayList<modelo.Actividad> actividades){
        for(modelo.Actividad actividad : actividades){
            Object data[] = {actividad.getNombre(), actividad.getDescripcion(), actividad.getHorario().toString()};
            this.tableModelAct.addRow(data);
        }
    }
    
    public void addArticulo(modelo.ArticuloAdmin articulo){
        if(articulo.getTipo().equals(util.TipoArticulo.MONTAJE)){
            this.cmbMontaje.addItem(articulo.getNombre());
        }
    }
    
    public void cargar(){
        try{
            this.removeItems();
            java.util.ArrayList<modelo.ArticuloAdmin> articulos = modeloDAO.ArticuloAdminDAO.getAll(Conexion.getConnection());
            for(modelo.ArticuloAdmin articulo : articulos){
                this.addArticulo(articulo);
            }
        }catch(SQLException e){
        }
    }
    
    private String getPrecio(String name) throws SQLException{
        modelo.ArticuloAdmin articulo = new modelo.ArticuloAdmin();
        articulo.setNombre(name);
        articulo = modeloDAO.ArticuloAdminDAO.buscarPorNombre(articulo, Conexion.getConnection());
        if(articulo != null){
            return ""+articulo.getPrecio();
        }
        return "";
    }
    
    private Integer index(String name){
        for(Integer i=1 ; i<this.cmbMontaje.getItemCount(); i++){
            if(name.equals(this.cmbMontaje.getItemAt(i))){
                return i;
            }
        }
        return -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticulo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtDoc = new javax.swing.JTextField();
        btnBus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbMontaje = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableActividades = new javax.swing.JTable();
        txtHoraInicio = new javax.swing.JTextField();
        txtMontoAbonado = new javax.swing.JTextField();
        btnDelArt = new javax.swing.JButton();
        btnAddArt = new javax.swing.JButton();
        btnAddAct = new javax.swing.JButton();
        btnDelAct = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblPrecioMontaje = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        txtAbonar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblMontoFalt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(738, 654));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Articulos"));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tableArticulo.setBackground(new java.awt.Color(255, 255, 255));
        tableArticulo.setForeground(new java.awt.Color(0, 0, 0));
        tableArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tableArticulo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Documento");

        txtDoc.setBackground(new java.awt.Color(0, 0, 51));
        txtDoc.setForeground(new java.awt.Color(255, 255, 255));

        btnBus.setBackground(new java.awt.Color(255, 255, 255));
        btnBus.setForeground(new java.awt.Color(0, 0, 0));
        btnBus.setText("Buscar");

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Monto abonado");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Hora de inicio");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Fecha de celebracion");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Montaje");

        cmbMontaje.setBackground(new java.awt.Color(255, 255, 255));
        cmbMontaje.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Precio         $ ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actividades"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        tableActividades.setBackground(new java.awt.Color(255, 255, 255));
        tableActividades.setForeground(new java.awt.Color(0, 0, 0));
        tableActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Hora inicio", "Descripcion"
            }
        ));
        jScrollPane2.setViewportView(tableActividades);
        if (tableActividades.getColumnModel().getColumnCount() > 0) {
            tableActividades.getColumnModel().getColumn(0).setResizable(false);
            tableActividades.getColumnModel().getColumn(1).setResizable(false);
            tableActividades.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtHoraInicio.setBackground(new java.awt.Color(0, 0, 51));
        txtHoraInicio.setForeground(new java.awt.Color(255, 255, 255));

        txtMontoAbonado.setEditable(false);
        txtMontoAbonado.setBackground(new java.awt.Color(0, 0, 51));
        txtMontoAbonado.setForeground(new java.awt.Color(255, 255, 255));

        btnDelArt.setBackground(new java.awt.Color(255, 255, 255));
        btnDelArt.setForeground(new java.awt.Color(0, 0, 0));
        btnDelArt.setText("Eliminar");

        btnAddArt.setBackground(new java.awt.Color(255, 255, 255));
        btnAddArt.setForeground(new java.awt.Color(0, 0, 0));
        btnAddArt.setText("Añadir");

        btnAddAct.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAct.setForeground(new java.awt.Color(0, 0, 0));
        btnAddAct.setText("Añadir");

        btnDelAct.setBackground(new java.awt.Color(255, 255, 255));
        btnDelAct.setForeground(new java.awt.Color(0, 0, 0));
        btnDelAct.setText("Eliminar");

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar cambios");

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");

        lblPrecioMontaje.setForeground(java.awt.Color.white);

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Monto faltante");

        txtAbonar.setBackground(new java.awt.Color(0, 0, 51));
        txtAbonar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Abonar");

        lblMontoFalt.setForeground(java.awt.Color.white);
        lblMontoFalt.setText("$");

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Precio total");

        txtPrecioTotal.setBackground(new java.awt.Color(0, 0, 51));
        txtPrecioTotal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBus))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDelArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAddAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDelAct, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHoraInicio)
                                    .addComponent(txtMontoAbonado)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAbonar)
                                    .addComponent(lblMontoFalt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbMontaje, 0, 139, Short.MAX_VALUE)
                                    .addComponent(lblPrecioMontaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBus)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnDelArt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddArt)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnDelAct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddAct)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMontaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecioMontaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoAbonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMontoFalt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAbonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAddAct;
    public javax.swing.JButton btnAddArt;
    public javax.swing.JButton btnBus;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnDelAct;
    public javax.swing.JButton btnDelArt;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> cmbMontaje;
    public com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblMontoFalt;
    public javax.swing.JLabel lblPrecioMontaje;
    private javax.swing.JTable tableActividades;
    private javax.swing.JTable tableArticulo;
    public javax.swing.JTextField txtAbonar;
    public javax.swing.JTextField txtDoc;
    public javax.swing.JTextField txtHoraInicio;
    public javax.swing.JTextField txtMontoAbonado;
    public javax.swing.JTextField txtPrecioTotal;
    // End of variables declaration//GEN-END:variables
}
