/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author kuroy
 */
public class formInicio extends javax.swing.JPanel implements Runnable{
    private final String URLIMAGENES[] = {"images/boda_1.PNG","images/boda_2.PNG","images/boda_3.PNG"};
    private final java.awt.Dimension dimension;
    /**
     * Creates new form formInicio
     */
    public formInicio() {
        initComponents();    
        this.dimension = lblFondo.getMaximumSize();
        (new Thread(this)).start();
    }
    
    public void initListener(java.awt.event.ActionListener e){
        this.btnBuscarEvento.addActionListener(e);
        this.btnModCliente.addActionListener(e);
        this.btnCrearEvento.addActionListener(e);
        this.btnUpdArt.addActionListener(e);
    }
    
    private void cambiarImagen(Integer i){        
        Icon icon = new ImageIcon(new ImageIcon(URLIMAGENES[i]).getImage().getScaledInstance((int)dimension.getWidth(), (int)dimension.getHeight(), Image.SCALE_DEFAULT));
        this.lblFondo.setIcon(icon);
    }
    
    @Override
    public void run() {
        Integer i = 0;
        while(true){
            this.cambiarImagen(i);
            i++;
            i = i<this.URLIMAGENES.length ? i : 0;
            try {
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
            }
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearEvento = new javax.swing.JButton();
        btnBuscarEvento = new javax.swing.JButton();
        btnUpdArt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnModCliente = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(606, 422));
        setLayout(null);

        btnCrearEvento.setBackground(new java.awt.Color(255, 255, 255));
        btnCrearEvento.setText("Crear evento");
        btnCrearEvento.setFocusable(false);
        add(btnCrearEvento);
        btnCrearEvento.setBounds(170, 330, 270, 23);

        btnBuscarEvento.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarEvento.setText("Buscar evento");
        btnBuscarEvento.setFocusable(false);
        add(btnBuscarEvento);
        btnBuscarEvento.setBounds(170, 360, 270, 23);

        btnUpdArt.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdArt.setText("Actualizar articulos");
        btnUpdArt.setFocusable(false);
        add(btnUpdArt);
        btnUpdArt.setBounds(170, 390, 270, 23);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Casa de Festejos El Shaddai");
        add(jLabel1);
        jLabel1.setBounds(10, 10, 580, 60);

        btnModCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnModCliente.setText("Registrar cliente");
        btnModCliente.setFocusable(false);
        add(btnModCliente);
        btnModCliente.setBounds(170, 300, 270, 23);

        lblFondo.setForeground(new java.awt.Color(51, 51, 51));
        lblFondo.setMaximumSize(new java.awt.Dimension(610, 430));
        lblFondo.setMinimumSize(new java.awt.Dimension(462, 322));
        add(lblFondo);
        lblFondo.setBounds(0, 0, 590, 440);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarEvento;
    public javax.swing.JButton btnCrearEvento;
    public javax.swing.JButton btnModCliente;
    public javax.swing.JButton btnUpdArt;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables

}
